## **Pulizia dati Progetto Finale**

In [75]:
# Importazione Librerie
import pandas as pd
import numpy as np

In [76]:
dist_center_raw=pd.read_csv("..\\data\\initial_data\\Distribution Center.csv")
events_raw=pd.read_csv("..\\data\\initial_data\\events.csv")
inv_items_raw=pd.read_csv("..\\data\\initial_data\\inventory_items.csv")
order_items_raw=pd.read_csv("..\\data\\initial_data\\order_items.csv")
orders_raw=pd.read_csv("..\\data\\initial_data\\orders.csv")
prod_raw=pd.read_csv("..\\data\\initial_data\\products.csv")
users_raw=pd.read_csv("..\\data\\initial_data\\Users.csv")

In [77]:
dist_center=dist_center_raw.copy()
events=events_raw.copy()
inv_items=inv_items_raw.copy()
order_items=order_items_raw.copy()
orders=orders_raw.copy()
prod=prod_raw.copy()
users=users_raw.copy()

### Distribution Center

In [78]:
dist_center.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     str
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [79]:
dist_center

   id                                         name
0   3                                   Houston TX
1   7                              Philadelphia PA
2   5                               New Orleans LA
3   4                               Los Angeles CA
4   8                                    Mobile AL
5   1                                   Memphis TN
6   2                                   Chicago IL
7   6  Port Authority of New York/New Jersey NY/NJ
8  10                                  Savannah GA
9   9                                Charleston SC

In [80]:
# Nessuna pulizia necessaria

In [81]:
dist_center.to_csv("..\\data\\clean_data\\distribution_center_clean.csv", index=False)

### Events

In [82]:
events.info()
# Dati Mancanti in user_id (utenti non registrati)

<class 'pandas.DataFrame'>
RangeIndex: 681828 entries, 0 to 681827
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      681828 non-null  str
 1   user_id         181828 non-null  float64
 2   finish          681828 non-null  int64
 3   event_type      681828 non-null  str
 4   traffic_source  681828 non-null  str
 5   state           681828 non-null  str
dtypes: float64(1), int64(1), str(4)
memory usage: 31.2 MB

In [83]:
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state
270956,31a33bf7-2392-4616-a089-575d885ea15f,NaN,3,cancel,Email,Florida
99447,f5635029-3568-4944-bef4-204b840b2866,NaN,1,product,Adwords,Shanghai
600189,b8597e0e-9c52-4ab0-8bc2-0e5e4ebd41d0,88402.0,7,purchase,Email,Gyeonggi-do
197573,1ba792d3-b898-4cd9-b5ec-7645f0a13f46,NaN,2,product,Email,Shanghai
65916,f79e0c00-1456-4264-94bb-4f82b1aebaad,NaN,1,product,Email,Bahia

In [84]:
# Aggiungiamo il country sfruttanfo state, che si trova anche nella tabella users
city_country_map = users[['state', 'country']].drop_duplicates()
events = events.merge(city_country_map, on='state', how='left')

In [85]:
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state,country
305058,771551df-02b0-49ff-9450-c9f6235089b6,NaN,3,cart,Email,Zhejiang,China
500037,9e9301d2-e43f-41a9-b0cd-ef9a82176def,NaN,3,cancel,Facebook,Minnesota,United States
218175,71570c12-c23e-48dc-b173-d74b8f140d62,NaN,2,product,YouTube,Idaho,United States
641652,4e5bea19-d192-422a-8018-865ad3b58d8c,55344.0,7,purchase,Adwords,Maranhão,Brasil
472838,63cdaa57-b319-42ce-ab6c-77112ac9adc6,NaN,3,cart,Facebook,Nordrhein-Westfalen,Germany

In [86]:
events.info()
# qualche dato mancante sul country

<class 'pandas.DataFrame'>
RangeIndex: 698847 entries, 0 to 698846
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      698847 non-null  str
 1   user_id         186210 non-null  float64
 2   finish          698847 non-null  int64
 3   event_type      698847 non-null  str
 4   traffic_source  698847 non-null  str
 5   state           698847 non-null  str
 6   country         698823 non-null  str
dtypes: float64(1), int64(1), str(5)
memory usage: 37.3 MB

In [87]:
events["country"]=events["country"].fillna("Unknown")

In [88]:
events.to_csv("..\\data\\clean_data\\events_clean.csv", index=False)

### Inventory Items

In [89]:
inv_items.info()
# I Dati Mancanti in sold_at vanno mantenuti così come sono, il dato mancante ci fa capire che un pezzo è ancora in stock
# Cambiare created_at e sold_at in datetime

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  str
 3   sold_at                         181404 non-null  str
 4   product_distribution_center_id  489823 non-null  int64
dtypes: int64(3), str(2)
memory usage: 18.7 MB

In [90]:
inv_items["created_at"] = inv_items["created_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["created_at"] = pd.to_datetime(inv_items["created_at"], utc=True)
inv_items["sold_at"] = inv_items["sold_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["sold_at"] = pd.to_datetime(inv_items["sold_at"], utc=True)

In [91]:
inv_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  datetime64[us, UTC]
 3   sold_at                         181404 non-null  datetime64[us, UTC]
 4   product_distribution_center_id  489823 non-null  int64
dtypes: datetime64[us, UTC](2), int64(3)
memory usage: 18.7 MB

In [92]:
inv_items.sample(5)

,id,product_id,created_at,sold_at,product_distribution_center_id
354409,69068,9455,2023-12-16 00:05:29+00:00,2024-01-06 19:02:29+00:00,3
8464,37179,14017,2025-06-11 16:44:56+00:00,2025-06-15 18:51:56+00:00,2
296784,273451,23063,2024-04-07 03:50:00+00:00,NaT,4
13125,465247,28580,2025-07-20 05:15:00+00:00,NaT,4
280026,141693,6952,2024-06-02 03:45:00+00:00,NaT,1

In [93]:
# Se creo una variabile che assume valore 0 se il prodotto è stato venduto e 1 se è ancora in stock, posso eliminare sold_at
# Inoltre se aggiungo il mese e l'anno di creazione posso eliminare anche created_at
inv_items['in_stock'] = inv_items['sold_at'].isna().astype(int)
inv_items['month_year_creation'] = inv_items['created_at'].dt.strftime('%b %Y')
# magari posso aggiungere la durata di permanenza in stock
inv_items["time_in_stock"] = inv_items["sold_at"] - inv_items["created_at"]
inv_items["days_in_stock"] = inv_items["time_in_stock"].dt.days

In [94]:
inv_items=inv_items[["id", "product_id", "product_distribution_center_id", "in_stock", "month_year_creation", "days_in_stock"]]
# days_in_stock avrà valore null se non è ancora stato venduto

In [95]:
inv_items.sample(5)

,id,product_id,product_distribution_center_id,in_stock,month_year_creation,days_in_stock
169483,343963,20722,7,1,Aug 2020,NaN
314515,9454,26746,2,1,Mar 2025,NaN
173045,54867,21283,7,0,Mar 2023,21.0
5223,337062,28420,6,1,Oct 2020,NaN
464321,116498,16992,1,1,Mar 2020,NaN

In [96]:
inv_items.to_csv("..\\data\\clean_data\\inventory_items_clean.csv", index=False)

### Order Items

In [97]:
order_items.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dei vari prodotti dell'ordine
# Cambiare le variabili con date in DateTime

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  str
 7   shipped_at         118292 non-null  str
 8   delivered_at       63933 non-null   str
 9   returned_at        18372 non-null   str
 10  sale_price         181404 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 15.2 MB

In [98]:
order_items["created_at"] = order_items["created_at"].str.replace(r"\.\d+", "", regex=True)
order_items["created_at"] = pd.to_datetime(order_items["created_at"], utc=True)
order_items["shipped_at"] = order_items["shipped_at"].str.replace(r"\.\d+", "", regex=True)
order_items["shipped_at"] = pd.to_datetime(order_items["shipped_at"], utc=True)
order_items["delivered_at"] = order_items["delivered_at"].str.replace(r"\.\d+", "", regex=True)
order_items["delivered_at"] = pd.to_datetime(order_items["delivered_at"], utc=True)
order_items["returned_at"] = order_items["returned_at"].str.replace(r"\.\d+", "", regex=True)
order_items["returned_at"] = pd.to_datetime(order_items["returned_at"], utc=True)

In [99]:
# Arrotondiamo sale_price
order_items["sale_price"]=order_items["sale_price"].round(2)

In [100]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  datetime64[us, UTC]
 7   shipped_at         118292 non-null  datetime64[us, UTC]
 8   delivered_at       63933 non-null   datetime64[us, UTC]
 9   returned_at        18372 non-null   datetime64[us, UTC]
 10  sale_price         181404 non-null  float64
dtypes: datetime64[us, UTC](4), float64(1), int64(5), str(1)
memory usage: 15.2 MB

In [101]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
31812,156610,108040,86471,2712,422852,Complete,2025-11-20 08:46:15+00:00,2025-11-20 18:58:23+00:00,2025-11-23 05:55:23+00:00,NaT,19.00
25001,161649,111421,89190,18196,436454,Complete,2025-12-18 13:12:19+00:00,2025-12-18 02:38:25+00:00,2025-12-18 17:15:25+00:00,NaT,16.00
42621,91234,63088,50481,1730,246179,Complete,2023-01-12 11:17:29+00:00,2023-01-12 15:31:05+00:00,2023-01-16 17:57:05+00:00,NaT,23.33
86975,93988,64992,52018,17230,253584,Complete,2023-07-16 06:33:45+00:00,2023-07-17 01:54:42+00:00,2023-07-17 12:28:42+00:00,NaT,39.44
31734,96271,66614,53287,14961,259806,Cancelled,2025-07-25 12:40:30+00:00,NaT,NaT,NaT,19.00

In [102]:
order_items=order_items[["id", "order_id", "user_id","product_id","inventory_item_id","status","sale_price"]]

In [103]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,sale_price
127756,148945,102769,82215,17272,402076,Processing,62.00
9773,73042,50529,40472,4079,197000,Shipped,10.78
114701,174582,120370,96330,7707,471343,Returned,52.99
117228,112912,77987,62364,27990,304723,Processing,54.98
148292,112691,77825,62237,13815,304126,Shipped,88.00

In [104]:
order_items.to_csv("..\\data\\clean_data\\order_items_clean.csv", index=False)

### Orders

In [105]:
orders.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dell'ordine
# Cambiare in datetime le variabili con le date

<class 'pandas.DataFrame'>
RangeIndex: 124988 entries, 0 to 124987
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124988 non-null  int64
 1   user_id       124988 non-null  int64
 2   status        124988 non-null  str
 3   created_at    124988 non-null  str
 4   returned_at   12635 non-null   str
 5   shipped_at    81363 non-null   str
 6   delivered_at  43863 non-null   str
 7   num_of_item   124988 non-null  int64
dtypes: int64(3), str(5)
memory usage: 7.6 MB

In [106]:
orders["created_at"] = orders["created_at"].str.replace(r"\.\d+", "", regex=True)
orders["created_at"] = pd.to_datetime(orders["created_at"], utc=True)
orders["shipped_at"] = orders["shipped_at"].str.replace(r"\.\d+", "", regex=True)
orders["shipped_at"] = pd.to_datetime(orders["shipped_at"], utc=True)
orders["returned_at"] = orders["returned_at"].str.replace(r"\.\d+", "", regex=True)
orders["returned_at"] = pd.to_datetime(orders["returned_at"], utc=True)
orders["delivered_at"] = orders["delivered_at"].str.replace(r"\.\d+", "", regex=True)
orders["delivered_at"] = pd.to_datetime(orders["delivered_at"], utc=True)

In [107]:
orders.sample(5)

,order_id,user_id,status,created_at,returned_at,shipped_at,delivered_at,num_of_item
119836,90996,72782,Shipped,2023-07-11 05:13:36+00:00,NaT,2023-07-14 02:58:36+00:00,NaT,1
48326,30116,24286,Shipped,2025-06-19 05:34:26+00:00,NaT,2025-06-21 07:32:26+00:00,NaT,1
66799,57436,45881,Cancelled,2023-07-31 10:09:50+00:00,NaT,NaT,NaT,1
84434,100743,80597,Complete,2024-05-27 20:30:20+00:00,NaT,2024-05-29 21:37:20+00:00,2024-06-01 11:22:20+00:00,1
104494,90261,72194,Returned,2025-11-20 07:43:34+00:00,2025-11-25 15:10:34+00:00,2025-11-20 16:22:34+00:00,2025-11-25 07:31:34+00:00,1

In [108]:
# Se aggiungiamo il mese e l'anno di creazione. E calcoliamo il tempo per spedire un ordine e per farlo arrivare:
# Ci servono ancora created_at, shipped_at, delivered_at, returned_at?

In [109]:
# Aggiunta mese e anno di creazione ordine
orders['month_year_creation'] = orders['created_at'].dt.strftime('%b %Y')
# Aggiunta tempo di spedizione e di consegna
orders["time_for_shipping"] = orders["shipped_at"] - orders["created_at"]
orders["time_for_delivery"] = orders["delivered_at"] - orders["shipped_at"]
orders["days_for_shipping"] = orders["time_for_shipping"].dt.days
orders["days_for_delivery"] = orders["time_for_delivery"].dt.days

In [110]:
orders["year"]=orders["created_at"].dt.year
orders["month"]=orders["created_at"].dt.month

In [111]:
orders=orders[["order_id","user_id","status","num_of_item","month_year_creation","days_for_shipping","days_for_delivery","year"]]

In [112]:
orders.sample(5)
# Ovviamente rimangono dati mancanti in days_for_shipping e days_for_delivery in base allo stato dell'ordine

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year
79594,62449,49964,Complete,1,Jan 2023,0.0,4.0,2023
119179,86635,69335,Shipped,1,Jan 2022,1.0,NaN,2022
12931,28241,22727,Complete,1,Mar 2025,2.0,4.0,2025
35520,105505,84386,Processing,2,Feb 2026,NaN,NaN,2026
92194,46301,37163,Processing,1,Jun 2024,NaN,NaN,2024

In [113]:
"""
Vogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.
Come possiamo fare:
1. Facciamo una join tra order_items e products
2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost
3. Calcoliamo il profitto per ogni prodotto: sale_price-cost
4. Raggruppiamo per order_id e sommiamo i costi e il profitto
5. Facciamo una join tra il nuovo dataframe e orders
"""

'\nVogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.\nCome possiamo fare:\n1. Facciamo una join tra order_items e products\n2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost\n3. Calcoliamo il profitto per ogni prodotto: sale_price-cost\n4. Raggruppiamo per order_id e sommiamo i costi e il profitto\n5. Facciamo una join tra il nuovo dataframe e orders\n'

In [114]:
df_merged1 = pd.merge(left=order_items, right=prod, how='inner', left_on='product_id', right_on='id')
df_merged1=df_merged1[["order_id","product_id","sale_price","cost"]]
df_merged1["profit_per_product"]=df_merged1["sale_price"]-df_merged1["cost"]
df_merged1.sample(5)

        order_id  product_id  sale_price      cost  profit_per_product
158236     43466       20497      109.50  40.51500            68.98500
1140       20649       15953        5.78   2.82064             2.95936
30951      47292       10234       18.78  12.00042             6.77958
76699      20619       27060       34.97  14.40764            20.56236
70042      60053        4015       31.98  15.47832            16.50168

In [115]:
cost_prof_per_order=df_merged1.groupby("order_id", as_index=False).agg({"sale_price":sum, "cost": sum, "profit_per_product": sum})
cost_prof_per_order = cost_prof_per_order.rename(columns={"profit_per_product": "profit"})
cost_prof_per_order["profit"]=cost_prof_per_order["profit"].round(2)
cost_prof_per_order["cost"]=cost_prof_per_order["cost"].round(2)
cost_prof_per_order.head()

   order_id  sale_price   cost  profit
0         1       73.10  34.90   38.20
1         2      156.99  67.52   89.47
2         3       29.99  15.98   14.01
3         4       80.63  44.02   36.61
4         5      158.00  89.45   68.55

In [116]:
orders=pd.merge(left=orders, right=cost_prof_per_order, how='inner', on='order_id')
orders.sample(5)
# fare attenzione allo stato dell'ordine. tenere conto del profitto solo per ordini completati, spediti o in processo.
# Per ordini cancellati il profitto si azzera.
# Per gli ordini resi il profitto potrebbe diventare negativo (profitto=-costo). Decidere insieme.

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year,sale_price,cost,profit
108720,16873,13501,Shipped,1,Jul 2022,0.0,NaN,2022,69.50,36.07,33.43
51559,51007,40834,Shipped,3,Apr 2023,0.0,NaN,2023,156.98,85.09,71.89
23154,110161,88166,Complete,1,Sep 2025,0.0,1.0,2025,169.00,97.34,71.66
66218,49703,39845,Cancelled,1,Nov 2025,NaN,NaN,2025,27.95,16.02,11.93
59537,104696,83740,Shipped,1,Aug 2023,2.0,NaN,2023,47.99,27.69,20.30

In [117]:
# Modifica profitto in base allo status dell'ordine
orders.loc[orders['status'] == 'Cancelled', 'profit'] = 0
orders.loc[orders['status'] == 'Returned', 'profit'] = 0

In [118]:
orders.sample(5)

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year,sale_price,cost,profit
71923,521,426,Complete,1,Aug 2025,1.0,1.0,2025,29.00,14.04,14.96
803,10784,8624,Cancelled,1,Oct 2025,NaN,NaN,2025,55.30,26.82,0.00
69489,93402,74749,Cancelled,1,Aug 2025,NaN,NaN,2025,18.99,8.47,0.00
20271,87032,69677,Complete,3,Oct 2023,1.0,0.0,2023,187.98,91.99,95.99
21928,100640,80500,Complete,1,Jan 2026,1.0,2.0,2026,359.00,176.63,182.37

In [119]:
orders.to_csv("..\\data\\clean_data\\orders_clean.csv", index=False)

### Products

In [120]:
prod.info()
# name e brand con Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 2.0 MB

In [121]:
prod["brand"]=prod["brand"].fillna("Unknown")

In [122]:
prod=prod[["id","cost","category","brand","retail_price","department","distribution_center_id"]]

In [123]:
prod.sample(5)

,id,cost,category,brand,retail_price,department,distribution_center_id
18376,1194,9.235380,Sweaters,LabelShopper,19.990000,Women,6
6604,5306,39.255448,Pants & Capris,Eddie Bauer,79.949997,Women,2
17909,6526,14.967150,Shorts,Henry Segal,28.950001,Women,6
27549,25778,11.900000,Underwear,Diesel,28.000000,Men,10
12426,27432,23.366150,Swim,Speedo,41.950001,Men,4

In [124]:
"""
La variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.
È un valore continuo, non arrotondato, e spesso deriva da:
- contratti con fornitori
- costi medi ponderati
- costi di produzione
- costi di importazione
- conversioni di valuta
- calcoli interni dell'azienda

Per questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.
"""

"\nLa variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.\nÈ un valore continuo, non arrotondato, e spesso deriva da:\n- contratti con fornitori\n- costi medi ponderati\n- costi di produzione\n- costi di importazione\n- conversioni di valuta\n- calcoli interni dell'azienda\n\nPer questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.\n"

In [125]:
# Arrotondiamo cost e retail_price
prod["cost"]=prod["cost"].round(2)
prod["retail_price"]=prod["retail_price"].round(2)

In [126]:
prod["ideal_profit"]=prod["retail_price"]-prod["cost"]

In [127]:
prod.sample(5)

,id,cost,category,brand,retail_price,department,distribution_center_id,ideal_profit
21460,6340,11.38,Shorts,Gloria Vanderbilt,24.95,Women,7,13.57
24264,19838,80.94,Suits & Sport Coats,A:X Armani Exchange,228.00,Men,8,147.06
26169,19085,64.88,Sweaters,Obermeyer,129.50,Men,9,64.62
2068,7649,258.96,Blazers & Jackets,Magaschoni,698.00,Women,1,439.04
23280,994,8.28,Sweaters,Curve Appeal,19.99,Women,8,11.71

In [128]:
prod.to_csv("..\\data\\clean_data\\products_clean.csv", index=False)

### Users

In [129]:
users.info()
# city ha Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   age             100000 non-null  int64
 4   gender          100000 non-null  str
 5   state           100000 non-null  str
 6   city            99005 non-null   str
 7   country         100000 non-null  str
 8   traffic_source  100000 non-null  str
dtypes: int64(2), str(7)
memory usage: 6.9 MB

In [130]:
users["city"]=users["city"].fillna("Unknown")

In [131]:
users["age"].describe()

count    100000.000000
mean         40.949600
std          17.023095
min          12.000000
25%          26.000000
50%          41.000000
75%          56.000000
max          70.000000
Name: age, dtype: float64

In [132]:
# Aggiunta categorie età per future analisi
bins = [0, 25, 45, 65, np.inf] 
labels = [ "Young", "Adult", "Middle-aged Adult", "Senior"] 
users["age_group"] = pd.cut(users["age"], bins=bins, labels=labels, right=False)

In [133]:
users.sample(5)

,id,first_name,last_name,age,gender,state,city,country,traffic_source,age_group
30663,54481,Heather,Ibarra,51,F,Guangdong,Yongzhou,China,Search,Middle-aged Adult
3048,35135,David,Clark,20,M,Arizona,Peoria,United States,Email,Young
34249,64672,Gail,Mitchell,60,F,Guangdong,Shanghai,China,Search,Middle-aged Adult
69642,56635,Stephanie,Nelson,12,F,Pará,Parauapebas,Brasil,Search,Young
13491,62178,Sandra,Ortega,34,F,California,Carlsbad,United States,Search,Adult

In [134]:
users.to_csv("..\\data\\clean_data\\users_clean.csv", index=False)