## **Pulizia dati Progetto Finale**

In [48]:
# Importazione Librerie
import pandas as pd
import numpy as np

In [49]:
dist_center_raw=pd.read_csv("..\\data\\initial_data\\Distribution Center.csv")
events_raw=pd.read_csv("..\\data\\initial_data\\events.csv")
inv_items_raw=pd.read_csv("..\\data\\initial_data\\inventory_items.csv")
order_items_raw=pd.read_csv("..\\data\\initial_data\\order_items.csv")
orders_raw=pd.read_csv("..\\data\\initial_data\\orders.csv")
prod_raw=pd.read_csv("..\\data\\initial_data\\products.csv")
users_raw=pd.read_csv("..\\data\\initial_data\\Users.csv")

In [50]:
dist_center=dist_center_raw.copy()
events=events_raw.copy()
inv_items=inv_items_raw.copy()
order_items=order_items_raw.copy()
orders=orders_raw.copy()
prod=prod_raw.copy()
users=users_raw.copy()

### Distribution Center

In [51]:
dist_center.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     str
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [52]:
dist_center

   id                                         name
0   3                                   Houston TX
1   7                              Philadelphia PA
2   5                               New Orleans LA
3   4                               Los Angeles CA
4   8                                    Mobile AL
5   1                                   Memphis TN
6   2                                   Chicago IL
7   6  Port Authority of New York/New Jersey NY/NJ
8  10                                  Savannah GA
9   9                                Charleston SC

In [53]:
# Nessuna pulizia necessaria

In [54]:
dist_center.to_csv("..\\data\\clean_data\\distribution_center_clean.csv", index=False)

### Events

In [55]:
events.info()
# Dati Mancanti in user_id (utenti non registrati)

<class 'pandas.DataFrame'>
RangeIndex: 681828 entries, 0 to 681827
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      681828 non-null  str
 1   user_id         181828 non-null  float64
 2   finish          681828 non-null  int64
 3   event_type      681828 non-null  str
 4   traffic_source  681828 non-null  str
 5   state           681828 non-null  str
dtypes: float64(1), int64(1), str(4)
memory usage: 31.2 MB

In [56]:
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state
455077,c54f036a-c85f-4358-9b7f-95ff28fd3d85,NaN,3,cancel,YouTube,England
667225,c7800bd6-844e-479e-a2aa-84efc6d05c09,60029.0,13,purchase,Facebook,England
35949,2430e82f-33d9-459d-b011-ea6e17e08b82,NaN,1,product,Email,Beijing
180938,977aee5d-3620-4ec1-b13e-e35c4329edd9,NaN,2,product,Email,Victoria
169633,04bfd342-8ae9-4de4-b82a-0ff142d048ac,NaN,2,product,Email,Andalucía

In [57]:
events["user_id"] = events["user_id"].fillna("Unknown")

In [58]:
# Aggiungiamo il country sfruttanfo state, che si trova anche nella tabella users
city_country_map = users[['state', 'country']].drop_duplicates()
events = events.merge(city_country_map, on='state', how='left')

In [59]:
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state,country
169898,a07b2972-6114-4b90-baae-a22dd3365a69,Unknown,2,product,Adwords,Rheinland-Pfalz,Germany
204426,591b19b6-a284-445f-a9bc-42b732a6be57,Unknown,2,product,Email,Florida,United States
447149,00bc7c8e-366b-42ff-82cd-7a26a7499c8b,Unknown,3,cancel,Email,Gyeongsangbuk-do,South Korea
434810,c5e17b9c-6224-4bd0-a226-d3937d024ba3,Unknown,3,cart,Email,Gyeonggi-do,South Korea
472779,907bd52a-0aad-442d-92d6-a5be07c7d62a,Unknown,3,cart,Email,Hainan,China

In [60]:
events.info()
# qualche dato mancante sul country

<class 'pandas.DataFrame'>
RangeIndex: 698847 entries, 0 to 698846
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      698847 non-null  str
 1   user_id         698847 non-null  object
 2   finish          698847 non-null  int64
 3   event_type      698847 non-null  str
 4   traffic_source  698847 non-null  str
 5   state           698847 non-null  str
 6   country         698823 non-null  str
dtypes: int64(1), object(1), str(5)
memory usage: 37.3+ MB

In [61]:
events["country"]=events["country"].fillna("Unknown")

In [62]:
events.to_csv("..\\data\\clean_data\\events_clean.csv", index=False)

### Inventory Items

In [63]:
inv_items.info()
# I Dati Mancanti in sold_at vanno mantenuti così come sono, il dato mancante ci fa capire che un pezzo è ancora in stock
# Cambiare created_at e sold_at in datetime

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  str
 3   sold_at                         181404 non-null  str
 4   product_distribution_center_id  489823 non-null  int64
dtypes: int64(3), str(2)
memory usage: 18.7 MB

In [64]:
inv_items["created_at"] = inv_items["created_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["created_at"] = pd.to_datetime(inv_items["created_at"], utc=True)
inv_items["sold_at"] = inv_items["sold_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["sold_at"] = pd.to_datetime(inv_items["sold_at"], utc=True)

In [65]:
inv_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  datetime64[us, UTC]
 3   sold_at                         181404 non-null  datetime64[us, UTC]
 4   product_distribution_center_id  489823 non-null  int64
dtypes: datetime64[us, UTC](2), int64(3)
memory usage: 18.7 MB

In [66]:
inv_items.sample(5)

,id,product_id,created_at,sold_at,product_distribution_center_id
206612,379163,23993,2024-05-01 02:47:00+00:00,NaT,3
418227,170384,12982,2021-05-28 06:43:51+00:00,2021-06-03 07:59:51+00:00,5
41120,349131,2473,2023-03-05 01:59:00+00:00,NaT,7
271238,465803,22705,2023-03-13 11:57:00+00:00,NaT,9
126143,62904,11298,2024-02-08 05:51:57+00:00,2024-03-25 07:28:57+00:00,7

In [ ]:
# Se creo una variabile che assume valore 0 se il prodotto è stato venduto e 1 se è ancora in stock, posso eliminare sold_at
# Inoltre se aggiungo il mese e l'anno di creazione posso eliminare anche created_at
inv_items['in_stock'] = inv_items['sold_at'].isna().astype(int)
inv_items['month_year_creation'] = inv_items['created_at'].dt.strftime('%b %Y')
# magari posso aggiungere la durata di permanenza in stock

In [68]:
inv_items=inv_items[["id", "product_id", "product_distribution_center_id", "in_stock", "month_year_creation"]]

In [69]:
inv_items.sample(5)

,id,product_id,product_distribution_center_id,in_stock,month_year_creation
25701,232258,29071,4,1,Sep 2021
155835,58888,21286,2,1,May 2025
344057,437443,24852,2,1,Nov 2020
24188,190097,28644,2,1,Dec 2024
297825,125126,7284,7,1,Apr 2024

In [70]:
inv_items.to_csv("..\\data\\clean_data\\inventory_items_clean.csv", index=False)

### Order Items

In [71]:
order_items.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dei vari prodotti dell'ordine
# Cambiare le variabili con date in DateTime

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  str
 7   shipped_at         118292 non-null  str
 8   delivered_at       63933 non-null   str
 9   returned_at        18372 non-null   str
 10  sale_price         181404 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 15.2 MB

In [72]:
order_items["created_at"] = order_items["created_at"].str.replace(r"\.\d+", "", regex=True)
order_items["created_at"] = pd.to_datetime(order_items["created_at"], utc=True)
order_items["shipped_at"] = order_items["shipped_at"].str.replace(r"\.\d+", "", regex=True)
order_items["shipped_at"] = pd.to_datetime(order_items["shipped_at"], utc=True)
order_items["delivered_at"] = order_items["delivered_at"].str.replace(r"\.\d+", "", regex=True)
order_items["delivered_at"] = pd.to_datetime(order_items["delivered_at"], utc=True)
order_items["returned_at"] = order_items["returned_at"].str.replace(r"\.\d+", "", regex=True)
order_items["returned_at"] = pd.to_datetime(order_items["returned_at"], utc=True)

In [73]:
# Arrotondiamo sale_price
order_items["sale_price"]=order_items["sale_price"].round(2)

In [74]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  datetime64[us, UTC]
 7   shipped_at         118292 non-null  datetime64[us, UTC]
 8   delivered_at       63933 non-null   datetime64[us, UTC]
 9   returned_at        18372 non-null   datetime64[us, UTC]
 10  sale_price         181404 non-null  float64
dtypes: datetime64[us, UTC](4), float64(1), int64(5), str(1)
memory usage: 15.2 MB

In [75]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
69948,39792,27633,22205,11217,107291,Cancelled,2021-11-22 06:10:51+00:00,NaT,NaT,NaT,31.98
101155,48188,33462,26989,19672,129900,Shipped,2025-09-06 16:04:30+00:00,2025-09-07 14:28:46+00:00,NaT,NaT,45.00
43009,89925,62190,49742,2117,242675,Cancelled,2025-01-16 23:56:45+00:00,NaT,NaT,NaT,23.95
159812,5656,3895,3094,3345,15190,Processing,2023-08-06 18:29:12+00:00,NaT,NaT,NaT,115.99
70912,10275,7149,5725,26029,27646,Processing,2025-07-11 20:05:22+00:00,NaT,NaT,NaT,32.00

In [76]:
# Se aggiungiamo il mese e l'anno di creazione. Ci servono ancora created_at, shipped_at, delivered_at, returned_at?

In [77]:
order_items.to_csv("..\\data\\clean_data\\order_items_clean.csv", index=False)

### Orders

In [78]:
orders.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dell'ordine
# Cambiare in datetime le variabili con le date

<class 'pandas.DataFrame'>
RangeIndex: 124988 entries, 0 to 124987
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124988 non-null  int64
 1   user_id       124988 non-null  int64
 2   status        124988 non-null  str
 3   created_at    124988 non-null  str
 4   returned_at   12635 non-null   str
 5   shipped_at    81363 non-null   str
 6   delivered_at  43863 non-null   str
 7   num_of_item   124988 non-null  int64
dtypes: int64(3), str(5)
memory usage: 7.6 MB

In [79]:
orders["created_at"] = orders["created_at"].str.replace(r"\.\d+", "", regex=True)
orders["created_at"] = pd.to_datetime(orders["created_at"], utc=True)
orders["shipped_at"] = orders["shipped_at"].str.replace(r"\.\d+", "", regex=True)
orders["shipped_at"] = pd.to_datetime(orders["shipped_at"], utc=True)
orders["returned_at"] = orders["returned_at"].str.replace(r"\.\d+", "", regex=True)
orders["returned_at"] = pd.to_datetime(orders["returned_at"], utc=True)
orders["delivered_at"] = orders["delivered_at"].str.replace(r"\.\d+", "", regex=True)
orders["delivered_at"] = pd.to_datetime(orders["delivered_at"], utc=True)

In [80]:
orders.sample(5)

,order_id,user_id,status,created_at,returned_at,shipped_at,delivered_at,num_of_item
110665,29876,24087,Shipped,2025-11-28 13:35:34+00:00,NaT,2025-11-30 04:03:34+00:00,NaT,1
12604,25375,20437,Complete,2025-07-09 12:53:38+00:00,NaT,2025-07-10 17:48:38+00:00,2025-07-13 00:33:38+00:00,1
2149,29399,23690,Cancelled,2024-08-23 05:45:33+00:00,NaT,NaT,NaT,2
72006,1298,1048,Complete,2024-10-19 12:00:03+00:00,NaT,2024-10-21 08:29:03+00:00,2024-10-25 08:44:03+00:00,1
7209,95742,76589,Cancelled,2026-02-14 21:58:39+00:00,NaT,NaT,NaT,2

In [81]:
"""
Vogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.
Come possiamo fare:
1. Facciamo una join tra order_items e products
2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost
3. Calcoliamo il profitto per ogni prodotto: sale_price-cost
4. Raggruppiamo per order_id e sommiamo i costi e il profitto
5. Facciamo una join tra il nuovo dataframe e orders
"""

'\nVogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.\nCome possiamo fare:\n1. Facciamo una join tra order_items e products\n2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost\n3. Calcoliamo il profitto per ogni prodotto: sale_price-cost\n4. Raggruppiamo per order_id e sommiamo i costi e il profitto\n5. Facciamo una join tra il nuovo dataframe e orders\n'

In [82]:
df_merged1 = pd.merge(left=order_items, right=prod, how='inner', left_on='product_id', right_on='id')
df_merged1=df_merged1[["order_id","product_id","sale_price","cost"]]
df_merged1["profit_per_product"]=df_merged1["sale_price"]-df_merged1["cost"]
df_merged1.sample(5)

        order_id  product_id  sale_price       cost  profit_per_product
52630      85415         168       25.00  13.650000           11.350000
161282     91393        8096      119.99  77.513539           42.476461
39182      94026       28591       21.99   8.224260           13.765740
114329     82298       22856       52.53  28.156079           24.373921
46849      44946        2790       24.99   9.746100           15.243900

In [83]:
cost_prof_per_order=df_merged1.groupby("order_id", as_index=False).agg({"sale_price":sum, "cost": sum, "profit_per_product": sum})
cost_prof_per_order = cost_prof_per_order.rename(columns={"profit_per_product": "profit"})
cost_prof_per_order["profit"]=cost_prof_per_order["profit"].round(2)
cost_prof_per_order["cost"]=cost_prof_per_order["cost"].round(2)
cost_prof_per_order.head()

   order_id  sale_price   cost  profit
0         1       73.10  34.90   38.20
1         2      156.99  67.52   89.47
2         3       29.99  15.98   14.01
3         4       80.63  44.02   36.61
4         5      158.00  89.45   68.55

In [84]:
orders=pd.merge(left=orders, right=cost_prof_per_order, how='inner', on='order_id')
orders.sample(5)
# fare attenzione allo stato dell'ordine. tenere conto del profitto solo per ordini completati, spediti o in processo.
# Per ordini cancellati il profitto si azzera.
# Per gli ordini resi il profitto potrebbe diventare negativo (profitto=-costo). Decidere insieme.

,order_id,user_id,status,created_at,returned_at,shipped_at,delivered_at,num_of_item,sale_price,cost,profit
5429,72014,57654,Cancelled,2022-11-26 07:05:00+00:00,NaT,NaT,NaT,1,59.99,20.88,39.11
118465,81821,65481,Shipped,2025-07-02 17:08:45+00:00,NaT,2025-07-04 16:38:45+00:00,NaT,4,106.04,48.70,57.34
108414,14883,11941,Shipped,2025-08-22 10:31:52+00:00,NaT,2025-08-23 02:23:52+00:00,NaT,1,44.00,24.68,19.32
85947,112983,90402,Complete,2023-11-27 19:07:40+00:00,NaT,2023-11-30 11:39:40+00:00,2023-12-02 16:25:40+00:00,1,198.00,108.70,89.30
50102,41636,33462,Shipped,2025-05-28 14:41:15+00:00,NaT,2025-05-28 20:03:15+00:00,NaT,1,69.95,28.47,41.48

In [85]:
# Modifica profitto in base allo status dell'ordine
orders.loc[orders['status'] == 'Cancelled', 'profit'] = 0
orders.loc[orders['status'] == 'Returned', 'profit'] = -orders['cost']

In [86]:
orders.sample(5)

,order_id,user_id,status,created_at,returned_at,shipped_at,delivered_at,num_of_item,sale_price,cost,profit
88258,7740,6183,Processing,2024-03-09 16:15:04+00:00,NaT,NaT,NaT,1,49.99,28.24,21.75
75364,28274,22755,Complete,2024-08-06 08:38:11+00:00,NaT,2024-08-08 09:27:11+00:00,2024-08-09 13:18:11+00:00,1,50.67,32.18,18.49
54727,72655,58144,Shipped,2025-11-03 08:30:05+00:00,NaT,2025-11-05 11:44:05+00:00,NaT,1,6.50,2.37,4.13
120431,94851,75882,Shipped,2025-08-14 21:59:35+00:00,NaT,2025-08-16 07:18:35+00:00,NaT,1,26.00,11.44,14.56
11844,19572,15714,Complete,2025-01-21 22:21:23+00:00,NaT,2025-01-24 18:21:23+00:00,2025-01-27 08:29:23+00:00,1,189.00,96.96,92.04

In [87]:
orders.to_csv("..\\data\\clean_data\\orders_clean.csv", index=False)

### Products

In [88]:
prod.info()
# name e brand con Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 2.0 MB

In [89]:
prod["name"]=prod["name"].fillna("Unknown")
prod["brand"]=prod["brand"].fillna("Unknown")

In [90]:
prod.sample(5)

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id
26607,22919,26.260000,Shorts,Quiksilver Thing Short - Men's,Quiksilver,52.000000,Men,B6102A2551C0B3CD2C13DAAEAB843F50,9
27717,10800,13.795500,Intimates,JockeyÂ® staycool Bikini - 3 pack,Jockey,25.500000,Women,D299A92004734135DE74355770B7C785,10
27064,3994,45.080000,Dresses,Lilly Pulitzer Women's Cassie Dress,Lilly Pulitzer,98.000000,Women,ADF8D7F8C53C8688E63A02BFB3055497,9
12080,4627,23.300581,Jeans,Levi's Women's 542 Capri,Levi's,42.990002,Women,0D1A9651497A38D8B1C3871C84528BD4,4
14093,1080,47.300000,Sweaters,Evolution by Cyrus Women's Sequins Cape Cardigan,Evolution by Cyrus,100.000000,Women,731C83DB8D2FF01BDC000083FD3C3740,4

In [91]:
"""
La variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.
È un valore continuo, non arrotondato, e spesso deriva da:
- contratti con fornitori
- costi medi ponderati
- costi di produzione
- costi di importazione
- conversioni di valuta
- calcoli interni dell'azienda

Per questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.
"""

"\nLa variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.\nÈ un valore continuo, non arrotondato, e spesso deriva da:\n- contratti con fornitori\n- costi medi ponderati\n- costi di produzione\n- costi di importazione\n- conversioni di valuta\n- calcoli interni dell'azienda\n\nPer questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.\n"

In [92]:
# Arrotondiamo cost e retail_price
prod["cost"]=prod["cost"].round(2)
prod["retail_price"]=prod["retail_price"].round(2)

In [93]:
# Togliamo sku
prod=prod[["id", "cost", "category", "name", "brand", "retail_price", "department", "distribution_center_id"]]

In [94]:
prod.sample(5)

,id,cost,category,name,brand,retail_price,department,distribution_center_id
9036,22741,23.95,Shorts,Carhartt Men's Work Short,Carhartt,49.80,Men,3
15761,15629,13.53,Plus,Woman Within Plus Size Petite jean pull on ela...,Woman Within,29.99,Women,5
24268,21021,71.42,Jeans,Armani Exchange Authentic Worn Jean,A:X Armani Exchange,128.00,Men,8
27072,7082,29.76,Shorts,Lilly Pulitzer Callahan Short 5 Shorts Hotty P...,Lilly Pulitzer,59.99,Women,9
1442,11529,19.92,Intimates,Cortland Plus Size Half Slip,Cortland,39.99,Women,1

In [95]:
prod.to_csv("..\\data\\clean_data\\products_clean.csv", index=False)

### Users

In [96]:
users.info()
# city ha Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   age             100000 non-null  int64
 4   gender          100000 non-null  str
 5   state           100000 non-null  str
 6   city            99005 non-null   str
 7   country         100000 non-null  str
 8   traffic_source  100000 non-null  str
dtypes: int64(2), str(7)
memory usage: 6.9 MB

In [97]:
users["city"]=users["city"].fillna("Unknown")

In [98]:
users.sample(5)

,id,first_name,last_name,age,gender,state,city,country,traffic_source
41524,12744,Donald,Thompson,33,M,Hebei,Handan,China,Search
76118,76811,Emily,Peterson,48,F,Santa Catarina,Videira,Brasil,Search
55266,28125,Edward,Norton,56,M,Maranhão,Balsas,Brasil,Organic
77193,21383,April,Gregory,26,F,Seoul,Seoul,South Korea,Search
60325,53653,Kimberly,Dixon,62,F,Nagano,Komaga Rane,Japan,Search

In [99]:
users.to_csv("..\\data\\clean_data\\users_clean.csv", index=False)