## **Pulizia dati Progetto Finale**

In [20]:
# Importazione Librerie
import pandas as pd
import numpy as np
from datetime import datetime, timezone

In [21]:
dist_center_raw=pd.read_csv("..\\data\\initial_data\\Distribution Center.csv")
events_raw=pd.read_csv("..\\data\\initial_data\\events.csv")
inv_items_raw=pd.read_csv("..\\data\\initial_data\\inventory_items.csv")
order_items_raw=pd.read_csv("..\\data\\initial_data\\order_items.csv")
orders_raw=pd.read_csv("..\\data\\initial_data\\orders.csv")
prod_raw=pd.read_csv("..\\data\\initial_data\\products.csv")
users_raw=pd.read_csv("..\\data\\initial_data\\Users.csv")

In [22]:
dist_center=dist_center_raw.copy()
events=events_raw.copy()
inv_items=inv_items_raw.copy()
order_items=order_items_raw.copy()
orders=orders_raw.copy()
prod=prod_raw.copy()
users=users_raw.copy()

### Distribution Center

In [23]:
dist_center.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     str
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [24]:
dist_center

   id                                         name
0   3                                   Houston TX
1   7                              Philadelphia PA
2   5                               New Orleans LA
3   4                               Los Angeles CA
4   8                                    Mobile AL
5   1                                   Memphis TN
6   2                                   Chicago IL
7   6  Port Authority of New York/New Jersey NY/NJ
8  10                                  Savannah GA
9   9                                Charleston SC

In [25]:
# Nessuna pulizia necessaria

In [26]:
dist_center.to_csv("..\\data\\clean_data\\distribution_center_clean.csv", index=False)

### Events

In [27]:
events.info()
# Dati Mancanti in user_id (utenti non registrati)
# created_at da trasformare in data

<class 'pandas.DataFrame'>
RangeIndex: 680812 entries, 0 to 680811
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      680812 non-null  str
 1   user_id         180812 non-null  float64
 2   finish          680812 non-null  int64
 3   event_type      680812 non-null  str
 4   traffic_source  680812 non-null  str
 5   state           680812 non-null  str
 6   created_at      680812 non-null  str
dtypes: float64(1), int64(1), str(5)
memory usage: 36.4 MB

In [28]:
events["created_at"] = events["created_at"].str.replace(r"\.\d+", "", regex=True)
events["created_at"] = pd.to_datetime(events["created_at"], utc=True)

In [29]:
events["year"]=events["created_at"].dt.year
events["month"]=events["created_at"].dt.month

In [30]:
events=events[["session_id","user_id","finish","event_type","traffic_source","state","year","month"]]
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state,year,month
307250,5a36355b-cd7b-4a75-ac30-53fad5eb0c9b,58209.0,5,purchase,Facebook,Henan,2026,1
313658,bb4fff98-bc09-4ed2-8bde-ef351cd8618a,92324.0,5,purchase,Email,Scotland,2020,2
447119,c186ada3-141d-4754-994c-89022ca7b19a,NaN,2,product,Adwords,Hubei,2026,2
599136,db14d90f-0b11-4eee-8c79-9ec1a96e099d,NaN,2,product,Email,Anhui,2019,5
652522,c38ac126-5edb-4a20-9533-2cf4321f8a43,NaN,1,product,YouTube,New South Wales,2023,1

In [31]:
# Dopo aver pulito Users aggiungiamo il country a events e salviamo il file pulito

### Inventory Items

In [32]:
inv_items.info()
# I Dati Mancanti in sold_at vanno mantenuti così come sono, il dato mancante ci fa capire che un pezzo è ancora in stock
# Cambiare created_at e sold_at in datetime

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  str
 3   sold_at                         181404 non-null  str
 4   product_distribution_center_id  489823 non-null  int64
dtypes: int64(3), str(2)
memory usage: 18.7 MB

In [33]:
inv_items["created_at"] = inv_items["created_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["created_at"] = pd.to_datetime(inv_items["created_at"], utc=True)
inv_items["sold_at"] = inv_items["sold_at"].str.replace(r"\.\d+", "", regex=True)
inv_items["sold_at"] = pd.to_datetime(inv_items["sold_at"], utc=True)

In [34]:
inv_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 489823 entries, 0 to 489822
Data columns (total 5 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              489823 non-null  int64
 1   product_id                      489823 non-null  int64
 2   created_at                      489823 non-null  datetime64[us, UTC]
 3   sold_at                         181404 non-null  datetime64[us, UTC]
 4   product_distribution_center_id  489823 non-null  int64
dtypes: datetime64[us, UTC](2), int64(3)
memory usage: 18.7 MB

In [35]:
inv_items.sample(5)

,id,product_id,created_at,sold_at,product_distribution_center_id
346452,93844,24987,2023-03-30 08:08:00+00:00,NaT,8
109212,26001,10698,2024-07-04 21:10:01+00:00,2024-07-14 19:12:01+00:00,5
441734,426542,437,2021-02-13 15:59:00+00:00,NaT,4
444780,363168,16745,2021-03-21 00:51:00+00:00,NaT,7
420009,141256,28114,2025-12-11 15:16:26+00:00,2026-01-16 00:52:26+00:00,5

In [36]:
# Se creo una variabile che assume valore 0 se il prodotto è stato venduto e 1 se è ancora in stock, posso eliminare sold_at
# Inoltre se aggiungo il mese e l'anno di creazione posso eliminare anche created_at
inv_items['in_stock'] = inv_items['sold_at'].isna().astype(int)
inv_items['month_year_creation'] = inv_items['created_at'].dt.strftime('%b %Y')
# magari posso aggiungere la durata di permanenza in stock (considerando i prodotti ancora non venduti come se venissero venduti alla data odierna)
oggi = datetime.now(timezone.utc).isoformat(sep=' ')
inv_items["sold_at"] = inv_items["sold_at"].fillna(oggi)
inv_items["time_in_stock"] = inv_items["sold_at"] - inv_items["created_at"]
inv_items["days_in_stock"] = inv_items["time_in_stock"].dt.days

In [37]:
inv_items=inv_items[["id", "product_id", "product_distribution_center_id", "in_stock", "month_year_creation", "days_in_stock"]]
# days_in_stock avrà valore null se non è ancora stato venduto

In [38]:
inv_items.sample(5)

,id,product_id,product_distribution_center_id,in_stock,month_year_creation,days_in_stock
431953,264020,13227,4,1,Aug 2024,545
88555,244995,17923,7,0,Aug 2025,45
420493,60323,13484,5,1,Jul 2024,591
13678,211936,13779,9,1,May 2024,650
416786,488098,27919,4,1,Jun 2023,988

In [39]:
inv_items.to_csv("..\\data\\clean_data\\inventory_items_clean.csv", index=False)

### Order Items

In [40]:
order_items.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dei vari prodotti dell'ordine
# Cambiare le variabili con date in DateTime

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  str
 7   shipped_at         118292 non-null  str
 8   delivered_at       63933 non-null   str
 9   returned_at        18372 non-null   str
 10  sale_price         181404 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 15.2 MB

In [41]:
order_items["created_at"] = order_items["created_at"].str.replace(r"\.\d+", "", regex=True)
order_items["created_at"] = pd.to_datetime(order_items["created_at"], utc=True)
order_items["shipped_at"] = order_items["shipped_at"].str.replace(r"\.\d+", "", regex=True)
order_items["shipped_at"] = pd.to_datetime(order_items["shipped_at"], utc=True)
order_items["delivered_at"] = order_items["delivered_at"].str.replace(r"\.\d+", "", regex=True)
order_items["delivered_at"] = pd.to_datetime(order_items["delivered_at"], utc=True)
order_items["returned_at"] = order_items["returned_at"].str.replace(r"\.\d+", "", regex=True)
order_items["returned_at"] = pd.to_datetime(order_items["returned_at"], utc=True)

In [42]:
# Arrotondiamo sale_price
order_items["sale_price"]=order_items["sale_price"].round(2)

In [43]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 181404 entries, 0 to 181403
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181404 non-null  int64
 1   order_id           181404 non-null  int64
 2   user_id            181404 non-null  int64
 3   product_id         181404 non-null  int64
 4   inventory_item_id  181404 non-null  int64
 5   status             181404 non-null  str
 6   created_at         181404 non-null  datetime64[us, UTC]
 7   shipped_at         118292 non-null  datetime64[us, UTC]
 8   delivered_at       63933 non-null   datetime64[us, UTC]
 9   returned_at        18372 non-null   datetime64[us, UTC]
 10  sale_price         181404 non-null  float64
dtypes: datetime64[us, UTC](4), float64(1), int64(5), str(1)
memory usage: 15.2 MB

In [44]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
162019,96884,67030,53636,8179,261468,Processing,2022-04-04 03:11:13+00:00,NaT,NaT,NaT,124.00
88872,47315,32857,26515,1651,127532,Shipped,2025-04-15 04:46:03+00:00,2025-04-16 06:06:49+00:00,NaT,NaT,39.95
66649,53671,37226,29998,13088,144692,Shipped,2021-12-02 19:36:35+00:00,2021-12-05 09:25:15+00:00,NaT,NaT,29.99
140242,166496,114738,91835,1223,449529,Complete,2025-10-03 05:44:32+00:00,2025-10-03 12:09:17+00:00,2025-10-03 18:48:17+00:00,NaT,75.00
107198,2505,1744,1379,2260,6740,Processing,2025-12-27 09:09:31+00:00,NaT,NaT,NaT,49.50

In [45]:
order_items=order_items[["id", "order_id", "user_id","product_id","inventory_item_id","status","sale_price"]]

In [46]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,sale_price
77299,48590,33747,27212,23339,130996,Complete,34.99
172362,88597,61281,49024,13838,239066,Returned,173.94
25026,15736,10966,8778,28307,42280,Processing,16.00
156858,89377,61819,49458,18816,241178,Processing,103.85
131979,742,511,418,16155,2009,Shipped,66.00

In [47]:
# Dobbiamo ancora inserire il profitto dei singoli prodotti di ogni ordine. Poi salviamo il csv

### Orders

In [48]:
orders.info()
# Dati Mancanti solo in shipped_at, delivered_at e returned_at. Vanno mantenuti, servono per capire lo stato dell'ordine
# Cambiare in datetime le variabili con le date

<class 'pandas.DataFrame'>
RangeIndex: 124988 entries, 0 to 124987
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124988 non-null  int64
 1   user_id       124988 non-null  int64
 2   status        124988 non-null  str
 3   created_at    124988 non-null  str
 4   returned_at   12635 non-null   str
 5   shipped_at    81363 non-null   str
 6   delivered_at  43863 non-null   str
 7   num_of_item   124988 non-null  int64
dtypes: int64(3), str(5)
memory usage: 7.6 MB

In [49]:
orders["created_at"] = orders["created_at"].str.replace(r"\.\d+", "", regex=True)
orders["created_at"] = pd.to_datetime(orders["created_at"], utc=True)
orders["shipped_at"] = orders["shipped_at"].str.replace(r"\.\d+", "", regex=True)
orders["shipped_at"] = pd.to_datetime(orders["shipped_at"], utc=True)
orders["returned_at"] = orders["returned_at"].str.replace(r"\.\d+", "", regex=True)
orders["returned_at"] = pd.to_datetime(orders["returned_at"], utc=True)
orders["delivered_at"] = orders["delivered_at"].str.replace(r"\.\d+", "", regex=True)
orders["delivered_at"] = pd.to_datetime(orders["delivered_at"], utc=True)

In [50]:
orders.sample(5)

,order_id,user_id,status,created_at,returned_at,shipped_at,delivered_at,num_of_item
10977,12682,10163,Complete,2024-10-24 12:05:02+00:00,NaT,2024-10-26 13:43:02+00:00,2024-10-28 13:47:02+00:00,1
93750,62259,49810,Processing,2022-04-08 23:24:07+00:00,NaT,NaT,NaT,1
61597,118531,94883,Shipped,2023-09-13 08:29:31+00:00,NaT,2023-09-15 20:53:31+00:00,NaT,1
15354,47919,38415,Complete,2022-09-16 23:02:11+00:00,NaT,2022-09-19 16:10:11+00:00,2022-09-23 23:45:11+00:00,1
68463,79791,63870,Cancelled,2024-03-17 08:44:28+00:00,NaT,NaT,NaT,1

In [51]:
# Se aggiungiamo il mese e l'anno di creazione. E calcoliamo il tempo per spedire un ordine e per farlo arrivare:
# Ci servono ancora created_at, shipped_at, delivered_at, returned_at?

In [52]:
# Aggiunta mese e anno di creazione ordine
orders['month_year_creation'] = orders['created_at'].dt.strftime('%b %Y')
# Aggiunta tempo di spedizione e di consegna
orders["time_for_shipping"] = orders["shipped_at"] - orders["created_at"]
orders["time_for_delivery"] = orders["delivered_at"] - orders["shipped_at"]
orders["days_for_shipping"] = orders["time_for_shipping"].dt.days
orders["days_for_delivery"] = orders["time_for_delivery"].dt.days

In [53]:
orders["year"]=orders["created_at"].dt.year
orders["month"]=orders["created_at"].dt.month

In [54]:
orders=orders[["order_id","user_id","status","num_of_item","month_year_creation","days_for_shipping","days_for_delivery","year","month"]]

In [55]:
orders.sample(5)
# Ovviamente rimangono dati mancanti in days_for_shipping e days_for_delivery in base allo stato dell'ordine

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year,month
67794,70713,56589,Cancelled,2,Jul 2023,NaN,NaN,2023,7
43241,112223,89823,Returned,1,Dec 2025,0.0,0.0,2025,12
34664,97563,78012,Processing,2,Jul 2025,NaN,NaN,2025,7
49423,37298,30061,Shipped,1,May 2019,1.0,NaN,2019,5
32154,72848,58294,Processing,1,Jul 2024,NaN,NaN,2024,7

In [56]:
"""
Vogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.
Come possiamo fare:
1. Facciamo una join tra order_items e products
2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost
3. Calcoliamo il profitto per ogni prodotto: sale_price-cost
4. Raggruppiamo per order_id e sommiamo i costi e il profitto
5. Facciamo una join tra il nuovo dataframe e orders
"""

'\nVogliamo aggiungere il costo, il prezzo di vendita e il profitto per ogni ordine.\nCome possiamo fare:\n1. Facciamo una join tra order_items e products\n2. Manteniamo nel nuovo dataframe solo order_id, product_id, sale_price e cost\n3. Calcoliamo il profitto per ogni prodotto: sale_price-cost\n4. Raggruppiamo per order_id e sommiamo i costi e il profitto\n5. Facciamo una join tra il nuovo dataframe e orders\n'

In [57]:
df_merged1 = pd.merge(left=order_items, right=prod, how='inner', left_on='product_id', right_on='id')
df_merged1=df_merged1[["order_id","product_id","sale_price","cost"]]
df_merged1["profit_per_product"]=df_merged1["sale_price"]-df_merged1["cost"]
df_merged1.sample(5)
# aggiungiamo il profitto dei singoli prodotti in order_items

       order_id  product_id  sale_price       cost  profit_per_product
48197     17409       26400       25.00  11.225000           13.775000
96834      1302         952       43.99  20.543331           23.446669
94867      5239        5211       42.00  23.562000           18.438000
36901    114086       17011       20.00  10.240000            9.760000
18074     26382       24603       13.99   8.491930            5.498070

### Finiamo di sitemare order_items

In [58]:
order_items=pd.merge(left=order_items, right=df_merged1, on=["order_id", "product_id"], how="left")

In [59]:
order_items=order_items[["id","order_id","user_id","product_id","inventory_item_id","status","sale_price_x","cost","profit_per_product"]]
order_items.rename(columns={"sale_price_x":"sale_price"}, inplace=True)

In [60]:
order_items.sample(5)

,id,order_id,user_id,product_id,inventory_item_id,status,sale_price,cost,profit_per_product
117996,620,424,347,22703,1677,Complete,55.00,24.915000,30.085000
173203,127411,87871,70321,4552,343935,Complete,179.00,97.376000,81.624000
90327,59878,41445,33305,26472,161473,Processing,39.99,17.075731,22.914269
43829,27545,19122,15344,25374,74136,Complete,24.00,10.704000,13.296000
106596,131024,90363,72267,17366,353703,Shipped,49.45,29.373300,20.076700

In [61]:
order_items["cost"]=order_items["cost"].round(2)
order_items["profit_per_product"]=order_items["profit_per_product"].round(2)

In [62]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 181416 entries, 0 to 181415
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  181416 non-null  int64
 1   order_id            181416 non-null  int64
 2   user_id             181416 non-null  int64
 3   product_id          181416 non-null  int64
 4   inventory_item_id   181416 non-null  int64
 5   status              181416 non-null  str
 6   sale_price          181416 non-null  float64
 7   cost                181416 non-null  float64
 8   profit_per_product  181416 non-null  float64
dtypes: float64(3), int64(5), str(1)
memory usage: 12.5 MB

In [63]:
order_items.to_csv("..\\data\\clean_data\\order_items_clean.csv", index=False)

### Torniamo ad orders

In [64]:
cost_prof_per_order=df_merged1.groupby("order_id", as_index=False).agg({"sale_price":sum, "cost": sum, "profit_per_product": sum})
cost_prof_per_order = cost_prof_per_order.rename(columns={"profit_per_product": "profit"})
cost_prof_per_order["profit"]=cost_prof_per_order["profit"].round(2)
cost_prof_per_order["cost"]=cost_prof_per_order["cost"].round(2)
cost_prof_per_order.head()

   order_id  sale_price   cost  profit
0         1       73.10  34.90   38.20
1         2      156.99  67.52   89.47
2         3       29.99  15.98   14.01
3         4       80.63  44.02   36.61
4         5      158.00  89.45   68.55

In [65]:
orders=pd.merge(left=orders, right=cost_prof_per_order, how='inner', on='order_id')
orders.sample(5)
# fare attenzione allo stato dell'ordine. tenere conto del profitto solo per ordini completati, spediti o in processo.
# Per ordini cancellati il profitto si azzera.
# Per gli ordini resi il profitto potrebbe diventare negativo (profitto=-costo). Decidere insieme.

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year,month,sale_price,cost,profit
43263,112542,90064,Returned,1,Feb 2024,2.0,2.0,2024,2,3.40,1.76,1.64
39140,33808,27256,Returned,1,Oct 2024,0.0,1.0,2024,10,12.61,6.23,6.38
45594,11651,9343,Shipped,4,Feb 2026,1.0,NaN,2026,2,150.90,77.39,73.51
25118,1460,1173,Processing,1,Feb 2026,NaN,NaN,2026,2,26.99,9.50,17.49
60368,110355,88336,Shipped,1,Feb 2026,2.0,NaN,2026,2,37.84,20.47,17.37

In [66]:
# Modifica profitto in base allo status dell'ordine
orders.loc[orders['status'] == 'Cancelled', 'profit'] = 0
orders.loc[orders['status'] == 'Returned', 'profit'] = 0

In [67]:
orders.sample(5)

,order_id,user_id,status,num_of_item,month_year_creation,days_for_shipping,days_for_delivery,year,month,sale_price,cost,profit
69181,89367,71480,Cancelled,1,Jan 2026,NaN,NaN,2026,1,19.98,10.45,0.00
32942,80508,64420,Processing,1,Dec 2023,NaN,NaN,2023,12,67.30,24.30,43.00
37883,8454,6748,Returned,2,Feb 2024,2.0,2.0,2024,2,46.35,24.93,0.00
99996,1254,1014,Returned,2,Nov 2024,2.0,2.0,2024,11,315.50,120.97,0.00
107641,9792,7829,Shipped,1,Oct 2025,2.0,NaN,2025,10,109.99,46.64,63.35

In [68]:
orders.to_csv("..\\data\\clean_data\\orders_clean.csv", index=False)

### Products

In [69]:
prod.info()
# name e brand con Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 2.0 MB

In [70]:
prod["brand"]=prod["brand"].fillna("Unknown")

In [71]:
prod=prod[["id","cost","category","brand","retail_price","department","distribution_center_id"]]

In [72]:
prod.sample(5)

,id,cost,category,brand,retail_price,department,distribution_center_id
14283,4914,19.160101,Jeans,Lee,34.900002,Women,5
2240,22368,18.700651,Pants,Bigmansland,42.990002,Men,1
25383,4094,8.610560,Jumpsuits & Rompers,Allegra K,17.360001,Women,9
4004,9943,18.623790,Sleep & Lounge,HUE,29.990000,Women,2
14398,13966,5.601600,Accessories,NEFF,14.400000,Women,5

In [73]:
"""
La variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.
È un valore continuo, non arrotondato, e spesso deriva da:
- contratti con fornitori
- costi medi ponderati
- costi di produzione
- costi di importazione
- conversioni di valuta
- calcoli interni dell'azienda

Per questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.
"""

"\nLa variabile cost è il costo sostenuto dall'azienda per acquistare o produrre quel prodotto.\nÈ un valore continuo, non arrotondato, e spesso deriva da:\n- contratti con fornitori\n- costi medi ponderati\n- costi di produzione\n- costi di importazione\n- conversioni di valuta\n- calcoli interni dell'azienda\n\nPer questo ha molti decimali. Non è un errore, è semplicemente un valore “raw”, non arrotondato.\n"

In [74]:
# Arrotondiamo cost e retail_price
prod["cost"]=prod["cost"].round(2)
prod["retail_price"]=prod["retail_price"].round(2)

In [75]:
# Non consideriamo i vari sconti del sale_price. Questo è il profitto ideale di ogni prodotto
prod["ideal_profit"]=prod["retail_price"]-prod["cost"]

In [76]:
prod.sample(5)

,id,cost,category,brand,retail_price,department,distribution_center_id,ideal_profit
28075,28142,18.72,Swim,Barracuda,32.00,Men,10,13.28
28924,10491,10.31,Intimates,Fruit of the Loom,18.00,Women,10,7.69
25215,2301,10.40,Fashion Hoodies & Sweatshirts,Allegra K,23.86,Women,9,13.46
3959,9076,7.10,Socks & Hosiery,HUE,20.00,Women,2,12.90
331,17298,45.47,Fashion Hoodies & Sweatshirts,Matix,78.00,Men,1,32.53

In [77]:
prod.to_csv("..\\data\\clean_data\\products_clean.csv", index=False)

### Users

In [78]:
users.info()
# city ha Dati Mancanti

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   age             100000 non-null  int64
 4   gender          100000 non-null  str
 5   state           100000 non-null  str
 6   city            99005 non-null   str
 7   country         100000 non-null  str
 8   traffic_source  100000 non-null  str
dtypes: int64(2), str(7)
memory usage: 6.9 MB

In [79]:
users["city"]=users["city"].fillna("Unknown")

In [80]:
users["age"].describe()

count    100000.000000
mean         40.949600
std          17.023095
min          12.000000
25%          26.000000
50%          41.000000
75%          56.000000
max          70.000000
Name: age, dtype: float64

In [81]:
# Aggiunta categorie età per future analisi
bins = [0, 25, 45, 65, np.inf] 
labels = [ "Young", "Adult", "Middle-aged Adult", "Senior"] 
users["age_group"] = pd.cut(users["age"], bins=bins, labels=labels, right=False)

In [82]:
users.sample(5)

,id,first_name,last_name,age,gender,state,city,country,traffic_source,age_group
87028,6702,Christopher,Scott,70,M,São Paulo,São Paulo,Brasil,Search,Senior
87542,81692,Alicia,Miller,26,F,São Paulo,Arujá,Brasil,Display,Adult
65259,7928,Theresa,Gallagher,42,F,Nordrhein-Westfalen,Siegen,Germany,Search,Adult
60793,63500,Anthony,Buckley,65,M,New Hampshire,Manchester,United States,Display,Senior
15280,46278,Chad,Anderson,29,M,Ceará,Tangente,Brasil,Search,Adult

In [83]:
users["country"].value_counts()

country
China             34051
United States     22456
Brasil            14579
South Korea        5230
France             4813
United Kingdom     4696
Germany            4184
Spain              3966
Japan              2382
Australia          2154
Belgium            1252
Poland              219
Colombia             14
Austria               2
Deutschland           1
España                1
Name: count, dtype: int64

In [84]:
# Sostituiamo "Deutschland" con "Germany" e "Espana" con "Spain"
users["country"] = users["country"].replace({"Deutschland": "Germany", "España": "Spain"})

In [85]:
users["country"].value_counts()

country
China             34051
United States     22456
Brasil            14579
South Korea        5230
France             4813
United Kingdom     4696
Germany            4185
Spain              3967
Japan              2382
Australia          2154
Belgium            1252
Poland              219
Colombia             14
Austria               2
Name: count, dtype: int64

In [86]:
users.to_csv("..\\data\\clean_data\\users_clean.csv", index=False)

### Finiamo di sistemare events

In [87]:
# Aggiungiamo il country sfruttanfo state, che si trova anche nella tabella users
city_country_map = users[['state', 'country']].drop_duplicates()
events = events.merge(city_country_map, on='state', how='left')

In [88]:
events.sample(5)

,session_id,user_id,finish,event_type,traffic_source,state,year,month,country
599381,d0bfe89d-ff66-4e33-9615-54fd2c724af8,NaN,3,cart,Email,Arizona,2021,6,United States
320515,efabf66c-07eb-4118-ad3d-1e90d2d407a7,NaN,3,cancel,Adwords,Florida,2019,7,United States
405688,e21ebb24-6583-486c-9f9e-3b0eb9f9788c,NaN,2,product,Email,Texas,2022,8,United States
60327,18c264e2-0567-43e7-a4e6-3aacc3724a37,NaN,3,cancel,YouTube,Texas,2025,12,United States
591408,4e7d62e7-5303-464c-ad53-f11c2d415e30,NaN,3,cart,Email,Beijing,2024,4,China

In [89]:
events.info()
# qualche dato mancante in Country

<class 'pandas.DataFrame'>
RangeIndex: 687427 entries, 0 to 687426
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   session_id      687427 non-null  str
 1   user_id         182539 non-null  float64
 2   finish          687427 non-null  int64
 3   event_type      687427 non-null  str
 4   traffic_source  687427 non-null  str
 5   state           687427 non-null  str
 6   year            687427 non-null  int32
 7   month           687427 non-null  int32
 8   country         687385 non-null  str
dtypes: float64(1), int32(2), int64(1), str(5)
memory usage: 42.0 MB

In [90]:
events["country"]=events["country"].fillna("Unknown")

In [91]:
events.to_csv("..\\data\\clean_data\\events_clean.csv", index=False)